### ISSUE TITLE
Add a page for every commitment

### ISSUE THREAD

**Issue by equivalentideas** [AOGPN/opengovernment.org.au#141]
Each commitment needs a page with:
1. A short summary of the commitment
2. A link to the full draft commitment document/web page (hopefully)
3. A link to the form where you can provide feedback (like [this](https://docs.google.com/forms/d/e/1FAIpQLSfQ0B8PN9fnjkMUItfHV3CXP6aRvSsWUIK70rZN57sAkAIfog/viewform))
4. A list of people who've provided feedback, and their feedback
5. The case for reform in this area, if we have this text
## Commitment reform areas

(this will be replaced with a list of the actual draft commitments when they are available)
- [x] <del>Extractives Transparency</del>  Natural Resource Transparency #148
- [x]     National Integrity Framework #147 (case for text published already)
- [x]     Improve whistle-blower protections in the tax and corporate sectors
- [x]     Beneficial Ownership - https://opengovernment.org.au/beneficial-ownership
- [x]     Release high-value datasets and enable data-driven innovation
- [x]    Build and maintain public trust to address concerns about data sharing
- [x]    Digitally transform the delivery of government services
- [x]     Information Management and access laws for the 21st century
- [x]     Understand the use of freedom of information
- [x]     Improve the discoverability and accessibility of government data and information
- [x]    Confidence in the electoral system and political parties - see 'case for' Political Action on Campaign Financing #151 and Politcal Party Eligibility to Receive Public Funding #152 
- [x]     Open contracting
- [x]     Delivery of Australia’s Open Government National Action Plan
- [x]     Enhance public participation in government decision making

**Comment by equivalentideas** [comment]
@kat can you drop the list of topic areas/pages we need to make on here?

**Comment by kat** [comment]
The list of commitments as it stands, per the minutes from 19th September Interim Working Group meeting are as follows. Civil society contacts for each commitment:

• Work towards compliance with the Extractive Industries Transparency Initiative. - - Mark /Phil Newman
• Improve whistle-blower protections in the corporate sector. Mark Zimsak/Phil Newman
• Assess Australia’s compliance with the Open Contracting Data Standard. - - Mark Zimsak/Peter Timmins
• Explore options for a beneficial ownership register for companies. Mark Zimsak/Phil Newman
• Improve whistle-blower protections in the corporate sector. Mark Zimsak/Phil Newman
• Digitally transforming the delivery of government services. ? PM&C - Helen Owens
• Delivery of Australia’s OGP National Action Plan. ? Maree Ashead
• Identify and release high-value datasets and enable data-driven innovation. Maree Ashead
• Build and maintain public trust to address concerns about data sharing. Maree Ashead

• Review and modernise information management and access laws Peter Timmins
• Enhanced integrity system (Attorney-General’s Department and Dr Coghill). Ken Coghill
• Confidence in electoral/political finance systems and political parties (Department of Finance and Dr Coghill). Ken Cohill
• Metrics on information access rights (PM&C, National Archives of Australia, Office of the Australian Information Commissioner, and Information and Privacy Commission NSW). Elisabeth Tydd (NSW Gov)
• Improve public participation and engagement (PM&C and Ms Szuminska). Kat Szuminska
Members discussed the possibility of merging the following proposed commitments:
• Improve the discoverability and accessibility of government information, with build public data infrastructure Maree Ashead

these were published at http://ogpau.govspace.gov.au/
(plus there will be another one about ...)
• Ongoing Dialogue with Gov & Civil Society - Peter, Kat

**Comment by kat** [comment]
@equivalentideas Need to rethink  2: A link to the full draft commitment document/web page (hopefully) 
because they're not published as a single webpage or individual web pages or documents only downloadable[ as a PDF or word document](http://ogpau.govspace.gov.au/have-your-say-on-australias-first-open-government-national-action-plan/)

**Comment by kat** [comment]
updated the list of commitments from official list published today by [PM&C](http://ogpau.govspace.gov.au/have-your-say-on-australias-first-open-government-national-action-plan/)

**Comment by kat** [comment]
beneficial ownership published with all the bits (I think) https://opengovernment.org.au/beneficial-ownership

**Comment by kat** [comment]
draft natural resources commitment published at https://opengovernment.org.au/natural-resource-transparency/ - need to go back and check values listed in the question on relevance to OGP values are the right ones! This is because PM&C have listed the values 'transparency and public accountability' but the OGP values are listed at http://www.opengovpartnership.org/sites/default/files/attachments/OGPvaluesguidancenote.pdf as follows: 
"In order to be marked of “clear relevance” in an OGP IRM report, a
commitment must clearly articulate their relationship to **Access to Information, Civic Participation, and
Public Accountability**" Transparency is part of the fourth value “Technology and Innovation for Transparency and Accountability”. This  "is instrumental in
achieving the other three values, governments that wish to have this value checked are advised to clearly articulate how technology and innovation will improve access to information, civic participation, and public accountability."

**Comment by kat** [comment]
have updated the form to include reference to the reform area - rather than just saying reform area - otherwise the full report details looks, rather unhelpfully like this
![screen shot 2016-10-31 at 20 35 17](https://cloud.githubusercontent.com/assets/95376/19849873/9b6354a8-9fa9-11e6-89eb-6088f41a866e.png) - because it doesn't display title of the form. That could get annoying if you have a couple of things you want to give feedback on and have a couple of tabs open that look identical!

**Comment by kat** [comment]
[Public trust in data sharing](https://opengovernment.org.au/public-trust-in-data-sharing/) up

**Comment by kat** [comment]
[Digital transformation](https://opengovernment.org.au/digital-transformation/)'s up

**Comment by kat** [comment]
and now - [Information management and access laws for the 21st century ](https://opengovernment.org.au/21st-century-information/)

**Comment by kat** [comment]
[Understand the use of Freedom of Information](https://opengovernment.org.au/understand-freedom-of-information-use/) is up

**Comment by kat** [comment]
[Improve the discoverability and accessibility of government data and information](https://opengovernment.org.au/improve-discoverability-and-accessibility-of-government-data-and-information/) up

**Comment by kat** [comment]
[Confidence in the electoral system and political parties](https://opengovernment.org.au/confidence-in-the-electoral-system-and-political-parties/) up

**Comment by kat** [comment]
draft [National Integrity Framework](https://docs.google.com/forms/d/e/1FAIpQLSfrmwtSy8q-YJI8-hLPhveq3LetnaMjj9PD-wXWH84Iop8u3w/viewform) commitment up

**Comment by kat** [comment]
[Open Contracting ](https://opengovernment.org.au/open-contracting/) too - nearly there!

**Comment by kat** [comment]
[Delivery of Australia's Open Government National Action Plan](Delivering Australia’s Open Government National Action Plan)

**Comment by kat** [comment]
lucky last! [Enhance public participation in government decision making](https://opengovernment.org.au/participation-in-government-decisions/) There are 'the cases for' to add. but for now I am calling this done!

**Comment by kat** [comment]
Please look @asherwolfie @equivalentideas  --> I have added cases for reform in [confidence in electoral system and political parties](https://opengovernment.org.au/confidence-in-th…olitical-parties/)  It might be better higher in the page? Please move if you can introduce it earlier in the piece.

**Comment by kat** [comment]
As above (and also maybe should be moved higher in the page) added link to[ The case for EITI](https://opengovernment.org.au/the-case-for-the-extractives-industry-transparency-initiative-eiti/) in [draft commitment on Natural Resource Transparency](https://opengovernment.org.au/natural-resource-transparency/) \* Added Supporting Organisations to the Case for page also.

**Comment by kat** [comment]
Updated the [Open Letter: Open data and digital transformation](https://opengovernment.org.au/open-letter-open-data-and-digital-transformation/) to link back to the three commitments mentioned here.

**Comment by kat** [comment]
Added the Case for a National Inegrity Framework to[ draft commitment: National Integrity Framework](https://opengovernment.org.au/national-integrity-framework/)
